## Here I attempt to classical solve and then create and quantum state of system at time t for the spring-ball oscillating system given in paper https://arxiv.org/pdf/2303.13012.pdf

In [1]:
import numpy as np
from scipy.integrate import odeint

In [8]:
#this is the ODE model for the classical solver for spring mass system
def spring_mass_system(y,t, M, K,N):

    # Extract positions and velocities
    positions = y[:N]
    velocities = y[N:]

    # Compute derivatives
    dydt = np.zeros_like(y)
    dydt[:N] = velocities
    dydt[N:] = np.dot(np.linalg.inv(M), -np.dot(K, positions))

    return dydt

#### Case : $$d = 1, E = 1, n = 2 \implies N = 4, \text{ no. of springs = 4 }, m_i = 1 \forall i \in [1,N], k_{i,j} \in [1,4], j>i, \forall (i,j) $$
$$\dot{\vec{x}}(0) = \begin{bmatrix} 1 \\ -1 \\ 0 \\  0 \end{bmatrix} \text{ and } \vec{x} = \begin{bmatrix} 0 \\ 0 \\ 0 \\ 0 \end{bmatrix}$$ 

In [9]:
#Initial conditions and inputs
N = 4
m = 1
E = 1
#mass matrix
M = np.diag(np.full(N,m)) 
#K matrix (spring constants)
k11 = 2
k12 = 1
k23 = 3
k34 = 2
K = np.array(([k11,k12,0,0],[k12,0,k23,0],[0,k23,0,k34],[0,0,k34,0]))

#position vector
x = np.zeros(4)
#velocity vector
x_dot = np.array([1,-1,0,0])

#initial condition
initial_y = np.concatenate((x,x_dot))

# Time vector
t = np.linspace(0, 10, 1000)

In [10]:
# Solve the ODE
solution = odeint(spring_mass_system, initial_y, t, args=(M, K,N))

# Extract positions and velocities from the solution
positions = solution[:, :N]
velocities = solution[:, N:]

# Print the results
print("Positions:")
print(positions)
print("\nVelocities:")
print(velocities)

Positions:
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00098383e-02 -1.00101817e-02  5.15133699e-07 -6.72369985e-12]
 [ 2.00186857e-02 -2.00213547e-02  4.00330757e-06 -1.83207132e-10]
 ...
 [ 3.88655597e+06 -2.20292375e+07  2.56393983e+07 -1.39797325e+07]
 [ 3.96178526e+06 -2.24556425e+07  2.61356831e+07 -1.42503295e+07]
 [ 4.03847072e+06 -2.28903010e+07  2.66415742e+07 -1.45261642e+07]]

Velocities:
[[ 1.00000000e+00 -1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 9.99949901e-01 -1.00005010e+00  1.50301900e-04 -2.89031044e-09]
 [ 9.99799620e-01 -1.00020046e+00  6.01222678e-04 -4.17352808e-08]
 ...
 [ 7.44359605e+06 -4.21908261e+07  4.91051239e+07 -2.67743358e+07]
 [ 7.58767672e+06 -4.30074857e+07  5.00556192e+07 -2.72925891e+07]
 [ 7.73454627e+06 -4.38399529e+07  5.10245126e+07 -2.78208738e+07]]


In [11]:
print("At time t = ", t[5], "the position vector is : ", positions[5], " and velocity vector is : ", velocities[5])

At time t =  0.050050050050050046 the position vector is :  [ 5.00291650e-02 -5.00709644e-02  6.26870808e-05 -1.60149244e-08]  and velocity vector is :  [ 9.98748283e-01 -1.00125460e+00  3.75829896e-03 -1.57386796e-06]
