In [1]:
import numpy as np
import pandas as pd

In [2]:
k1 = 20
k2 = 30
k3 = 20

m1 = 1
m2 = 1

In [3]:
# laplacian
F = np.array([[k1+k2, -k2],[-k2, k2+k3]])
print(F)

[[ 50 -30]
 [-30  50]]


In [4]:
#incidence matrix
B = np.array([[k1,-k2,0],[0,k2,-k3]])
print(B)

[[ 20 -30   0]
 [  0  30 -20]]


In [5]:
M = np.array([[m1,0],[0,m2]])
print(M)
M_sqrt = np.sqrt(M)
print(M_sqrt)

[[1 0]
 [0 1]]
[[1. 0.]
 [0. 1.]]


In [7]:
B_new = np.matmul(np.linalg.inv(M),B)
print(B_new)

[[ 20. -30.   0.]
 [  0.  30. -20.]]


In [9]:
B_new_dagger = B_new.conj().T
print(B_new_dagger)

[[ 20.   0.]
 [-30.  30.]
 [  0. -20.]]


In [10]:
Zeros_new = np.array([[0,0],[0,0]])
Zeros_new_dagger = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(Zeros_new)
print(Zeros_new_dagger)

[[0 0]
 [0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
H = -1 * np.array([[0,0,k1,-k2,0],[0,0,0,k2,-k3],[k1,0,0,0,0],[-k2,k2,0,0,0],[0,-k3,0,0,0]])
print(H)

[[  0   0 -20  30   0]
 [  0   0   0 -30  20]
 [-20   0   0   0   0]
 [ 30 -30   0   0   0]
 [  0  20   0   0   0]]
