## Here I attempt to define the Hamiltonian for the spring-ball oscillating system given in paper https://arxiv.org/pdf/2303.13012.pdf

Following largely from section 3 of the paper

- $ H = -\begin{bmatrix} 0 & B \\ B^\dagger & 0 \end{bmatrix} $ where dim of $B$ is $N \text{x} M$, therefore $dim(H) = (N+M) \text{x} (N+M)$
- We pad $B$ with zeros such that $dim (B) = N^2 \text{x}N^2$ (according to appendix A1 and A4), therefore $dim(H) = 2N^2 \text{x} 2N^2$
- Now for $B$ we have, $BB^\dagger = A$, $ \begin{equation}
  \sqrt{M}B|j,k\rangle =
    \begin{cases}
      \sqrt{k_{jj}}|j\rangle & \text{if } j=k \\
      \sqrt{k_{jk}}(|j\rangle-|k\rangle) & \text{if } j<k\\
    \end{cases}       
\end{equation} $ and elements of $B^\dagger$ are either $\sqrt{k_{jk}/m_j}$ or $0$.

- $ A$ = $\sqrt{M}^{-1] F \sqrt{M}^{-1} $.

- $M$ is diagonal matrix of masses $(m_{jj}>0)$ and $F$ is the $N \text{x} N$ matrix whose diagonal and off-diagonal entries are $f_{jj} = \sum_k \kappa_{jk}$ and $f_{jk} = -\kappa_{jk}$,respectively. 

for the second point in $|j,k\rangle$ state is in vector [00,11,22,33,01,02,03,12,13,23]

#### Case : $$d = 1, E = 1, n = 2 \implies N = 4, \text{ no. of springs = 4 }, m_i = 1 \forall i \in [1,N], k_{i,j} \in [1,4], j>i, \forall (i,j) $$
$$\dot{\vec{x}}(0) = \begin{bmatrix} 1 \\ -1 \\ 0 \\  0 \end{bmatrix} \text{ and } \vec{x} = \begin{bmatrix} 0 \\ 0 \\ 0 \\ 0 \end{bmatrix}$$ 

In [1]:
import numpy as np

In [2]:
N = 4
m = 1
E = 1
#mass matrix
M = np.diag(np.full(N,m)) 
#K matrix (spring constants)
k11 = 2
k12 = 1
k23 = 3
k34 = 2
K = np.array(([k11,k12,0,0],[k12,0,k23,0],[0,k23,0,k34],[0,0,k34,0]))

# Matrix F
F = np.zeros((N,N))
for j in range(N):
    for k in range(N):
        if j==k:
            F[j][k] = sum(K[j]) 
        else:
            F[j][k] = -K[j][k]

print(M, len(M), len(M[0]))
print(K, len(K), len(K[0]))
print(F, len(F), len(F[0]))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 4 4
[[2 1 0 0]
 [1 0 3 0]
 [0 3 0 2]
 [0 0 2 0]] 4 4
[[ 3. -1.  0.  0.]
 [-1.  4. -3.  0.]
 [ 0. -3.  5. -2.]
 [ 0.  0. -2.  2.]] 4 4


In [4]:
#sqrt(M)B Matrix
sqM_B = np.zeros((N,int(N*(N+1)/2)))
count = 0 #this will keep track of the coloumn of B based on |j,k>
for j in range(N):
    for k in range(N):
        if j==k:
            sqM_B[j][k] = np.sqrt(K[j][j])
        elif j<k:
            sqM_B[j][N+count] = np.sqrt(K[j][k])
            sqM_B[k][N+count] = -np.sqrt(K[j][k])
            count+=1

print(sqM_B)

[[ 1.41421356  0.          0.          0.          1.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.         -1.          0.
   0.          1.73205081  0.          0.        ]
 [ 0.          0.          0.          0.          0.         -0.
   0.         -1.73205081  0.          1.41421356]
 [ 0.          0.          0.          0.          0.          0.
  -0.          0.         -0.         -1.41421356]]


In [70]:
#check if sqM_B is correct
state_jk_list = np.identity(10)
out = np.matmul(sqM_B,state_jk_list)
print(np.transpose(out))

[[ 1.41421356  0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 1.         -1.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          1.73205081 -1.73205081  0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          1.41421356 -1.41421356]]


 Matrices B and B_dag
 
 Since we have $\sqrt{M}B$ we can get $B$ by $\sqrt{M}^{-1}\sqrt{M}B$

In [71]:
#geting inverse of sqrt{M}
sqM_inv = np.linalg.inv(np.sqrt(M))
#B matrix
B = np.matmul(sqM_inv,sqM_B)
#B dagger matrix
B_dag = np.matrix(B).getH()
print(B,B_dag)

[[ 1.41421356  0.          0.          0.          1.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.         -1.          0.
   0.          1.73205081  0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.         -1.73205081  0.          1.41421356]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.         -1.41421356]] [[ 1.41421356  0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 1.         -1.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          1.73205081 -1.73205081  0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          1.41421356 -1.41421356]]


In [80]:
# Checking if formed B and B_dag is correct
#1) Check in size of B is NxM and B_dag is MxN
if len(B)==N and len(B[0])==int(N*(N+1)/2):
    print("Dimensions of Matrix B is correct")
else:
    print("Dimension of B is incorrect")
    
if B_dag.shape[1]==N and B_dag.shape[0]==int(N*(N+1)/2): #since B_dag is numpy matrix not numpy array
    print("Dimensions of Matrix B_dag is correct")
else:
    print("Dimensions of B_dag is incorrect")

#2) Check if B*B_dag = A
A = np.matmul(sqM_inv,np.matmul(F,sqM_inv))
print("B*B_dag = A:", np.allclose(np.matmul(B,B_dag),A))

Dimensions of Matrix B is correct
Dimensions of Matrix B_dag is correct
B*B_dag = A: True


## Finally we pad B and B_dagger according to pt. 2

In [88]:
pad_B = np.pad(B,((0,int(N**2-N)),(0,int(N**2-(N*(N+1)/2)))),"constant")
pad_B_dag = np.matrix(pad_B).getH()

# Finally Our Hamiltonian 

In [119]:
temp1 = np.concatenate((-np.identity(N**2),-pad_B),axis = 1)
temp2 = np.concatenate((-np.array(pad_B_dag), -np.identity(N**2)),axis = 1)
H = np.concatenate((temp1,temp2),axis = 0)

In [120]:
len(H),len(H[0])

(32, 32)